CREATE TABLE "UserProfile" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "college" TEXT, "degree" TEXT, "graduationYear" INTEGER, "skills" JSONB NOT NULL, "experience" JSONB NOT NULL, "projects" JSONB NOT NULL, "portfolio" TEXT, "github" TEXT, "linkedin" TEXT, "location" TEXT, "preferredRoles" JSONB NOT NULL, "preferredLocations" JSONB NOT NULL, "confirmedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UserProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Resume" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "fileName" TEXT NOT NULL, "storagePath" TEXT NOT NULL, "extractedText" TEXT, "extractedData" JSONB, "confirmedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Resume_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobSearch" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "missionId" TEXT, "role" TEXT NOT NULL, "location" TEXT NOT NULL, "postedWithinHours" INTEGER NOT NULL, "remoteOnly" BOOLEAN NOT NULL DEFAULT false, "status" TEXT NOT NULL, "sourceStatuses" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), CONSTRAINT "JobSearch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Job" ("id" TEXT NOT NULL, "searchId" TEXT NOT NULL, "source" TEXT NOT NULL, "sourceJobId" TEXT NOT NULL, "title" TEXT NOT NULL, "company" TEXT NOT NULL, "location" TEXT NOT NULL, "remoteStatus" TEXT, "employmentType" TEXT, "description" TEXT NOT NULL, "postedAt" TIMESTAMP(3), "applicationUrl" TEXT NOT NULL, "sourceUrl" TEXT NOT NULL, "skills" JSONB NOT NULL, "experience" TEXT, "salary" TEXT, "logoUrl" TEXT, "extractedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Job_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JobMatch" ("id" TEXT NOT NULL, "searchId" TEXT NOT NULL, "jobId" TEXT NOT NULL, "score" INTEGER NOT NULL, "matchedSkills" JSONB NOT NULL, "missingSkills" JSONB NOT NULL, "experienceMatch" BOOLEAN NOT NULL, "educationMatch" BOOLEAN NOT NULL, "locationMatch" BOOLEAN NOT NULL, "reasons" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "JobMatch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Shortlist" ("id" TEXT NOT NULL, "jobId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'SHORTLISTED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Shortlist_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Application" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "jobId" TEXT NOT NULL, "status" TEXT NOT NULL, "applicationUrl" TEXT NOT NULL, "confirmationId" TEXT, "submittedAt" TIMESTAMP(3), "verifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Application_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ApplicationField" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "fieldName" TEXT NOT NULL, "profilePath" TEXT, "value" TEXT, "confidence" DOUBLE PRECISION NOT NULL, "status" TEXT NOT NULL, CONSTRAINT "ApplicationField_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ApplicationEvent" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "message" TEXT NOT NULL, "evidence" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ApplicationEvent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "UserProfile_userId_key" ON "UserProfile"("userId");
CREATE INDEX "Resume_profileId_createdAt_idx" ON "Resume"("profileId", "createdAt");
CREATE INDEX "JobSearch_profileId_createdAt_idx" ON "JobSearch"("profileId", "createdAt");
CREATE UNIQUE INDEX "Job_source_sourceJobId_key" ON "Job"("source", "sourceJobId");
CREATE INDEX "Job_searchId_postedAt_idx" ON "Job"("searchId", "postedAt");
CREATE UNIQUE INDEX "JobMatch_searchId_jobId_key" ON "JobMatch"("searchId", "jobId");
CREATE INDEX "JobMatch_searchId_score_idx" ON "JobMatch"("searchId", "score");
CREATE UNIQUE INDEX "Shortlist_jobId_key" ON "Shortlist"("jobId");
CREATE UNIQUE INDEX "Application_jobId_key" ON "Application"("jobId");
CREATE INDEX "Application_profileId_status_idx" ON "Application"("profileId", "status");
CREATE INDEX "ApplicationField_applicationId_status_idx" ON "ApplicationField"("applicationId", "status");
CREATE INDEX "ApplicationEvent_applicationId_createdAt_idx" ON "ApplicationEvent"("applicationId", "createdAt");
ALTER TABLE "Resume" ADD CONSTRAINT "Resume_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JobSearch" ADD CONSTRAINT "JobSearch_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JobSearch" ADD CONSTRAINT "JobSearch_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "Mission"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Job" ADD CONSTRAINT "Job_searchId_fkey" FOREIGN KEY ("searchId") REFERENCES "JobSearch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JobMatch" ADD CONSTRAINT "JobMatch_searchId_fkey" FOREIGN KEY ("searchId") REFERENCES "JobSearch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JobMatch" ADD CONSTRAINT "JobMatch_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Shortlist" ADD CONSTRAINT "Shortlist_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApplicationField" ADD CONSTRAINT "ApplicationField_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApplicationEvent" ADD CONSTRAINT "ApplicationEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
