"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useState } from "react";

const demoGoal = "Find suitable software engineering internships posted in the last 48 hours and prepare applications.";
const examples = ["Research the latest climate policy updates and summarize primary sources.", "Find suitable software engineering internships posted in the last 48 hours and prepare applications.", "Compare three accessible project management tools for a small design team."];

export default function HomePage() {
  const [goal, setGoal] = useState(demoGoal); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function createMission() { setBusy(true); setMessage(""); try { const response = await fetch("/api/missions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ goal }) }); const body = (await response.json()) as { id?: string; error?: string }; if (!response.ok || !body.id) throw new Error(body.error ?? "Mission could not be created"); window.location.href = `/missions/${body.id}`; } catch (error) { setMessage(error instanceof Error ? error.message : "Unexpected error"); setBusy(false); } }
  return <main className="landing"><div className="noise" /><header className="topbar landing-top"><a className="brand" href="/">NEXUS <span>AI MISSION CONTROL</span></a><nav><a href="/dashboard">Evaluation</a><span className="live-dot">Local runtime</span></nav></header><section className="hero"><div className="hero-copy"><p className="eyebrow cyan">AUTONOMOUS WORK / HUMAN CONTROL</p><h1>NEXUS</h1><p className="hero-lede">From a simple goal to real-world results.</p><p className="hero-description">An autonomous AI agent that plans, acts, verifies, recovers and proves what it did — with humans in control.</p><button className="primary-button" onClick={() => document.getElementById("mission-form")?.scrollIntoView({ behavior: "smooth" })}>Start a mission <span>↗</span></button></div><div className="hero-orbit" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-core"><span>N</span></div><div className="orbit-label label-one">PLAN</div><div className="orbit-label label-two">VERIFY</div><div className="orbit-label label-three">PROVE</div></div></section><section className="capabilities"><div className="section-mark">01 / CAPABILITIES</div><div className="capability-grid">{[["01", "Browser + API + MCP tools", "A controlled tool surface for real-world work."], ["02", "Autonomous planning", "Structured steps from one natural-language goal."], ["03", "Evidence-based verification", "No green check without observed proof."], ["04", "Human approval", "Consequential actions stop at the gate."], ["05", "Automatic recovery", "Bounded retries when reality disagrees."]].map(([number, title, description]) => <article key={number} className="capability"><span>{number}</span><h2>{title}</h2><p>{description}</p></article>)}</div></section><section className="mission-create" id="mission-form"><div className="section-mark">02 / NEW MISSION</div><div className="create-layout"><div><p className="eyebrow cyan">THE CONTROL SURFACE</p><h2>What should NEXUS accomplish?</h2><p className="muted">Give the agent a goal. It will turn intent into a plan, observe every action, and pause before anything consequential.</p></div><div className="form-panel"><textarea aria-label="Mission goal" value={goal} onChange={(event) => setGoal(event.target.value)} /><div className="form-footer"><span className="char-count">{goal.length} / 2000</span><button className="primary-button" onClick={createMission} disabled={busy || goal.length < 10}>{busy ? "Creating mission..." : "Start mission"}<span>→</span></button></div>{message && <p className="error-banner">{message}</p>}<div className="examples"><span className="label">Try an example</span>{examples.map((example) => <button key={example} onClick={() => setGoal(example)}>{example}</button>)}</div></div></div></section><footer className="landing-footer"><span>NEXUS / MISSION CONTROL</span><span>Observable autonomy, by design.</span></footer></main>;
}
