"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useState } from "react";

type Job = { id: string; source: string; title: string; company: string; location: string; remoteStatus: string | null; employmentType: string | null; description: string; postedAt: string | null; applicationUrl: string; sourceUrl: string; skills: string[]; matches: Array<{ score: number; matchedSkills: string[]; missingSkills: string[]; reasons: string[] }>; application: { id: string; status: string } | null };

export function JobDetailView({ jobId }: { jobId: string }) {
  const [job, setJob] = useState<Job | null>(null); const [error, setError] = useState(""); const [profileId, setProfileId] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([fetch(`/api/jobs/${jobId}`), fetch("/api/profile?userId=local-user")]).then(async ([jobResponse, profileResponse]) => { const jobBody = await jobResponse.json(); const profileBody = await profileResponse.json(); if (!jobResponse.ok) setError(jobBody.error ?? "Job unavailable"); else { setJob(jobBody); setProfileId(profileBody?.id ?? ""); } }); }, [jobId]);
  async function prepare() { if (!profileId) { setMessage("Confirm your profile before preparing an application."); return; } const response = await fetch("/api/applications/prepare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profileId, jobId }) }); const body = await response.json(); setMessage(response.ok ? "Application preview prepared. Review it before opening the external application page." : body.error); }
  if (error) return <main className="app-shell"><p className="error-banner">{error}</p></main>; if (!job) return <main className="app-shell"><div className="skeleton skeleton-large" /></main>;
  const match = job.matches[0];
  return <main className="app-shell"><header className="topbar"><a className="brand" href="/">NEXUS <span>MISSION CONTROL</span></a><nav><a className="text-link" href="/jobs">Back to jobs</a><a className="text-link" href="/profile">Profile</a></nav></header><section className="job-detail"><div className="job-detail-head"><div><span className="source-tag">{job.source}</span><h1>{job.title}</h1><p className="job-company">{job.company}</p><p className="muted">{job.location} {job.remoteStatus ? `· ${job.remoteStatus}` : ""} {job.employmentType ? `· ${job.employmentType}` : ""}</p></div>{match && <div className="detail-score"><strong>{match.score}%</strong><span>profile match</span></div>}</div><div className="job-detail-grid"><article><p className="eyebrow">Description</p><div className="job-long-description">{job.description}</div><p className="eyebrow">Skills from source</p><div className="skill-list">{job.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></article><aside className="detail-side"><div className="evidence-box"><p className="eyebrow">Source evidence</p><p className="muted">Extracted from {job.source}</p><a href={job.sourceUrl} target="_blank" rel="noreferrer">Open source listing ↗</a><p className="muted">{job.postedAt ? `Posted ${new Date(job.postedAt).toLocaleString()}` : "Posting date not provided"}</p></div>{match && <div className="evidence-box"><p className="eyebrow">Relevance analysis</p><p>{match.reasons.join(" ")}</p><p className="label">Matched skills</p><p className="muted">{match.matchedSkills.join(", ") || "None confirmed"}</p><p className="label">Missing skills</p><p className="muted">{match.missingSkills.join(", ") || "None detected"}</p></div>}<button className="primary-button" onClick={() => void prepare()} disabled={Boolean(job.application)}>{job.application ? job.application.status : "Prepare application"}<span>→</span></button>{message && <p className="success-note">{message}</p>}</aside></div></section></main>;
}
