"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useState } from "react";

type Profile = { id?: string; name: string; email: string; phone?: string | null; college?: string | null; degree?: string | null; graduationYear?: number | null; skills: string[]; location?: string | null; preferredRoles: string[]; preferredLocations: string[]; confirmedAt?: string | null };
const empty: Profile = { name: "", email: "", phone: "", college: "", degree: "", graduationYear: null, skills: [], location: "", preferredRoles: ["Software Engineering Intern"], preferredLocations: ["India"] };

export function ProfileForm() {
  const [profile, setProfile] = useState<Profile>(empty);
  const [skillText, setSkillText] = useState("");
  const [message, setMessage] = useState("");
  const [saved, setSaved] = useState(false);
  useEffect(() => { void fetch("/api/profile?userId=local-user").then(async (response) => { const body = await response.json(); if (body) { setProfile(body); setSkillText((body.skills ?? []).join(", ")); } }); }, []);
  function update(field: keyof Profile, value: string) { setProfile((current) => ({ ...current, [field]: field === "graduationYear" ? (value ? Number(value) : null) : value })); }
  async function save(confirmed: boolean) { setMessage(""); const response = await fetch("/api/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...profile, userId: "local-user", skills: skillText.split(",").map((value) => value.trim()).filter(Boolean), preferredRoles: profile.preferredRoles, preferredLocations: profile.preferredLocations, confirmed }) }); const body = await response.json(); if (!response.ok) setMessage(body.error ?? "Profile could not be saved"); else { setProfile(body); setSaved(true); setMessage(confirmed ? "Profile confirmed. NEXUS may use these details for application preparation." : "Profile saved."); } }
  return <main className="app-shell"><header className="topbar"><a className="brand" href="/">NEXUS <span>MISSION CONTROL</span></a><nav><a className="nav-button" href="/jobs">Jobs</a><a className="nav-button" href="/applications">Applications</a><a className="nav-button" href="/">New mission</a></nav></header><section className="page-heading"><p className="eyebrow cyan">Profile / confirmed data</p><h1>Give NEXUS the facts.</h1><p className="muted heading-copy">Only confirmed information may be used to prepare an application. NEXUS will leave unknown form fields untouched.</p></section><section className="profile-grid"><div className="form-panel profile-panel">{[["name", "Full name"], ["email", "Email"], ["phone", "Phone"], ["college", "College"], ["degree", "Degree"], ["graduationYear", "Graduation year"], ["location", "Location"]].map(([field, label]) => <label className="field-label" key={field}>{label}<input value={String(profile[field as keyof Profile] ?? "")} onChange={(event) => update(field as keyof Profile, event.target.value)} /></label>)}<label className="field-label">Skills <input value={skillText} onChange={(event) => setSkillText(event.target.value)} placeholder="React, TypeScript, Node.js" /></label><div className="form-footer"><button className="ghost-button" onClick={() => save(false)}>Save profile</button><button className="primary-button" onClick={() => save(true)}>Confirm profile <span>→</span></button></div>{message && <p className={saved ? "success-note" : "error-banner"}>{message}</p>}</div><aside className="profile-aside"><p className="eyebrow">Privacy boundary</p><h2>Nothing guessed.</h2><p className="muted">NEXUS can map confirmed fields to application forms. Ambiguous fields stay empty and require your input.</p><div className="data-chip"><span className="label">Profile status</span><br /><strong>{profile.confirmedAt ? "CONFIRMED" : "NEEDS CONFIRMATION"}</strong></div></aside></section></main>;
}
